# Generated by Django 5.2 on 2025-06-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selectielijst_api_service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which service to use to query the Selectielijst API.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zgw_consumers.service",
                        verbose_name="selectielijst API service",
                    ),
                ),
            ],
            options={
                "verbose_name": "API configuration",
                "verbose_name_plural": "API configurations",
            },
        ),
    ]
