# Generated by Django 5.2.3 on 2025-09-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
        ("zgw_consumers", "0025_service_jwt_valid_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconfig",
            name="objecttypen_api_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Which service to use to query the Objecttypen API.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="objecttypen API service",
            ),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="selectielijst_api_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Which service to use to query the Selectielijst API.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="selectielijst API service",
            ),
        ),
    ]
