export type ZaaktypenLoaderData = object;

/**
 * Zaaktypen loader.
 * Loader data can be obtained using `useLoaderData()` in ZaaktypenPage.
 */
export async function zaaktypenLoader(): Promise<ZaaktypenLoaderData> {
  const demoData = [
    {
      id: 1,
      name: "John Doe",
      age: 30,
      email: "john.doe@example.com",
      status: "Active",
    },
    {
      id: 2,
      name: "Jane Smith",
      age: 25,
      email: "jane.smith@example.com",
      status: "Inactive",
    },
    {
      id: 3,
      name: "Alice Johnson",
      age: 35,
      email: "alice.johnson@example.com",
      status: "Active",
    },
    {
      id: 4,
      name: "Bob Brown",
      age: 40,
      email: "bob.brown@example.com",
      status: "Pending",
    },
    {
      id: 5,
      name: "Charlie Davis",
      age: 28,
      email: "charlie.davis@example.com",
      status: "Active",
    },
    {
      id: 6,
      name: "David Clark",
      age: 33,
      email: "david.clark@example.com",
      status: "Inactive",
    },
    {
      id: 7,
      name: "Emma Wilson",
      age: 27,
      email: "emma.wilson@example.com",
      status: "Active",
    },
    {
      id: 8,
      name: "George King",
      age: 45,
      email: "george.king@example.com",
      status: "Pending",
    },
    {
      id: 9,
      name: "Hannah Scott",
      age: 23,
      email: "hannah.scott@example.com",
      status: "Active",
    },
    {
      id: 10,
      name: "Ian Harris",
      age: 38,
      email: "ian.harris@example.com",
      status: "Inactive",
    },
    {
      id: 11,
      name: "Jack Miller",
      age: 32,
      email: "jack.miller@example.com",
      status: "Active",
    },
    {
      id: 12,
      name: "Kathy Allen",
      age: 30,
      email: "kathy.allen@example.com",
      status: "Pending",
    },
    {
      id: 13,
      name: "Leo Carter",
      age: 36,
      email: "leo.carter@example.com",
      status: "Inactive",
    },
    {
      id: 14,
      name: "Megan Walker",
      age: 29,
      email: "megan.walker@example.com",
      status: "Active",
    },
    {
      id: 15,
      name: "Nathan Adams",
      age: 41,
      email: "nathan.adams@example.com",
      status: "Pending",
    },
    {
      id: 16,
      name: "Olivia Evans",
      age: 26,
      email: "olivia.evans@example.com",
      status: "Inactive",
    },
    {
      id: 17,
      name: "Paul Thomas",
      age: 39,
      email: "paul.thomas@example.com",
      status: "Active",
    },
    {
      id: 18,
      name: "Quincy Lewis",
      age: 31,
      email: "quincy.lewis@example.com",
      status: "Inactive",
    },
    {
      id: 19,
      name: "Rachel Moore",
      age: 34,
      email: "rachel.moore@example.com",
      status: "Pending",
    },
    {
      id: 20,
      name: "Sammy Taylor",
      age: 37,
      email: "sammy.taylor@example.com",
      status: "Active",
    },
    {
      id: 21,
      name: "Tina Murphy",
      age: 25,
      email: "tina.murphy@example.com",
      status: "Inactive",
    },
    {
      id: 22,
      name: "Ursula Parker",
      age: 42,
      email: "ursula.parker@example.com",
      status: "Active",
    },
    {
      id: 23,
      name: "Victor Green",
      age: 28,
      email: "victor.green@example.com",
      status: "Pending",
    },
    {
      id: 24,
      name: "Wendy Baker",
      age: 33,
      email: "wendy.baker@example.com",
      status: "Inactive",
    },
    {
      id: 25,
      name: "Xander Nelson",
      age: 29,
      email: "xander.nelson@example.com",
      status: "Active",
    },
    {
      id: 26,
      name: "Yvonne Carter",
      age: 35,
      email: "yvonne.carter@example.com",
      status: "Pending",
    },
    {
      id: 27,
      name: "Zane Price",
      age: 24,
      email: "zane.price@example.com",
      status: "Inactive",
    },
    {
      id: 28,
      name: "Anna King",
      age: 32,
      email: "anna.king@example.com",
      status: "Active",
    },
    {
      id: 29,
      name: "Brent Campbell",
      age: 40,
      email: "brent.campbell@example.com",
      status: "Inactive",
    },
    {
      id: 30,
      name: "Cindy Foster",
      age: 27,
      email: "cindy.foster@example.com",
      status: "Pending",
    },
    {
      id: 31,
      name: "Derrick James",
      age: 43,
      email: "derrick.james@example.com",
      status: "Active",
    },
    {
      id: 32,
      name: "Eleanor Martin",
      age: 22,
      email: "eleanor.martin@example.com",
      status: "Inactive",
    },
    {
      id: 33,
      name: "Felix Rogers",
      age: 36,
      email: "felix.rogers@example.com",
      status: "Pending",
    },
    {
      id: 34,
      name: "Grace Perry",
      age: 38,
      email: "grace.perry@example.com",
      status: "Active",
    },
    {
      id: 35,
      name: "Henry Clark",
      age: 41,
      email: "henry.clark@example.com",
      status: "Inactive",
    },
    {
      id: 36,
      name: "Ivy Bennett",
      age: 29,
      email: "ivy.bennett@example.com",
      status: "Pending",
    },
    {
      id: 37,
      name: "Jackie Mitchell",
      age: 33,
      email: "jackie.mitchell@example.com",
      status: "Active",
    },
    {
      id: 38,
      name: "Kyle Cooper",
      age: 45,
      email: "kyle.cooper@example.com",
      status: "Inactive",
    },
    {
      id: 39,
      name: "Lara Richardson",
      age: 31,
      email: "lara.richardson@example.com",
      status: "Active",
    },
    {
      id: 40,
      name: "Mark Collins",
      age: 36,
      email: "mark.collins@example.com",
      status: "Pending",
    },
    {
      id: 41,
      name: "Nina Edwards",
      age: 28,
      email: "nina.edwards@example.com",
      status: "Inactive",
    },
    {
      id: 42,
      name: "Owen Bell",
      age: 34,
      email: "owen.bell@example.com",
      status: "Active",
    },
    {
      id: 43,
      name: "Penny Harris",
      age: 39,
      email: "penny.harris@example.com",
      status: "Pending",
    },
    {
      id: 44,
      name: "Quinn Stevens",
      age: 26,
      email: "quinn.stevens@example.com",
      status: "Inactive",
    },
    {
      id: 45,
      name: "Rick Bennett",
      age: 38,
      email: "rick.bennett@example.com",
      status: "Active",
    },
    {
      id: 46,
      name: "Sharon Ross",
      age: 40,
      email: "sharon.ross@example.com",
      status: "Pending",
    },
    {
      id: 47,
      name: "Tommy Cooper",
      age: 27,
      email: "tommy.cooper@example.com",
      status: "Inactive",
    },
    {
      id: 48,
      name: "Ursula Evans",
      age: 32,
      email: "ursula.evans@example.com",
      status: "Active",
    },
    {
      id: 49,
      name: "Vince Foster",
      age: 29,
      email: "vince.foster@example.com",
      status: "Pending",
    },
    {
      id: 50,
      name: "Willie Patterson",
      age: 35,
      email: "willie.patterson@example.com",
      status: "Inactive",
    },
    {
      id: 51,
      name: "Xander Roberts",
      age: 27,
      email: "xander.roberts@example.com",
      status: "Active",
    },
    {
      id: 52,
      name: "Yasmin Campbell",
      age: 41,
      email: "yasmin.campbell@example.com",
      status: "Pending",
    },
    {
      id: 53,
      name: "Zachary Davis",
      age: 30,
      email: "zachary.davis@example.com",
      status: "Inactive",
    },
    {
      id: 54,
      name: "Amelia Moore",
      age: 22,
      email: "amelia.moore@example.com",
      status: "Active",
    },
    {
      id: 55,
      name: "Benjamin White",
      age: 32,
      email: "benjamin.white@example.com",
      status: "Inactive",
    },
    {
      id: 56,
      name: "Caitlin Ross",
      age: 39,
      email: "caitlin.ross@example.com",
      status: "Pending",
    },
    {
      id: 57,
      name: "Derek Watson",
      age: 30,
      email: "derek.watson@example.com",
      status: "Active",
    },
    {
      id: 58,
      name: "Eva Young",
      age: 34,
      email: "eva.young@example.com",
      status: "Inactive",
    },
    {
      id: 59,
      name: "Felipe Mitchell",
      age: 29,
      email: "felipe.mitchell@example.com",
      status: "Pending",
    },
    {
      id: 60,
      name: "Gina Johnson",
      age: 40,
      email: "gina.johnson@example.com",
      status: "Active",
    },
    {
      id: 61,
      name: "Hugo Clark",
      age: 31,
      email: "hugo.clark@example.com",
      status: "Inactive",
    },
    {
      id: 62,
      name: "Isabelle Taylor",
      age: 33,
      email: "isabelle.taylor@example.com",
      status: "Pending",
    },
    {
      id: 63,
      name: "Jesse Lee",
      age: 25,
      email: "jesse.lee@example.com",
      status: "Active",
    },
    {
      id: 64,
      name: "Kayla Harris",
      age: 42,
      email: "kayla.harris@example.com",
      status: "Inactive",
    },
    {
      id: 65,
      name: "Liam Mitchell",
      age: 37,
      email: "liam.mitchell@example.com",
      status: "Pending",
    },
    {
      id: 66,
      name: "Maya Price",
      age: 30,
      email: "maya.price@example.com",
      status: "Active",
    },
    {
      id: 67,
      name: "Nora Turner",
      age: 41,
      email: "nora.turner@example.com",
      status: "Inactive",
    },
    {
      id: 68,
      name: "Oscar White",
      age: 28,
      email: "oscar.white@example.com",
      status: "Pending",
    },
    {
      id: 69,
      name: "Paul Allen",
      age: 35,
      email: "paul.allen@example.com",
      status: "Active",
    },
    {
      id: 70,
      name: "Quincy Johnson",
      age: 34,
      email: "quincy.johnson@example.com",
      status: "Inactive",
    },
    {
      id: 71,
      name: "Rosa Martinez",
      age: 28,
      email: "rosa.martinez@example.com",
      status: "Pending",
    },
    {
      id: 72,
      name: "Steve Robinson",
      age: 38,
      email: "steve.robinson@example.com",
      status: "Active",
    },
    {
      id: 73,
      name: "Tasha Adams",
      age: 40,
      email: "tasha.adams@example.com",
      status: "Inactive",
    },
    {
      id: 74,
      name: "Ulysses Simmons",
      age: 41,
      email: "ulysses.simmons@example.com",
      status: "Pending",
    },
    {
      id: 75,
      name: "Vera Campbell",
      age: 29,
      email: "vera.campbell@example.com",
      status: "Active",
    },
    {
      id: 76,
      name: "Warren King",
      age: 33,
      email: "warren.king@example.com",
      status: "Inactive",
    },
    {
      id: 77,
      name: "Xena Phillips",
      age: 30,
      email: "xena.phillips@example.com",
      status: "Pending",
    },
    {
      id: 78,
      name: "Yuri Hall",
      age: 35,
      email: "yuri.hall@example.com",
      status: "Active",
    },
    {
      id: 79,
      name: "Zoe James",
      age: 39,
      email: "zoe.james@example.com",
      status: "Inactive",
    },
    {
      id: 80,
      name: "Aaron Thompson",
      age: 26,
      email: "aaron.thompson@example.com",
      status: "Pending",
    },
    {
      id: 81,
      name: "Beatrice Walker",
      age: 34,
      email: "beatrice.walker@example.com",
      status: "Active",
    },
    {
      id: 82,
      name: "Carlos Garcia",
      age: 40,
      email: "carlos.garcia@example.com",
      status: "Inactive",
    },
    {
      id: 83,
      name: "Diana Carter",
      age: 33,
      email: "diana.carter@example.com",
      status: "Pending",
    },
    {
      id: 84,
      name: "Elias Hernandez",
      age: 35,
      email: "elias.hernandez@example.com",
      status: "Active",
    },
    {
      id: 85,
      name: "Felicity Wilson",
      age: 42,
      email: "felicity.wilson@example.com",
      status: "Inactive",
    },
    {
      id: 86,
      name: "Gabe Phillips",
      age: 28,
      email: "gabe.phillips@example.com",
      status: "Pending",
    },
    {
      id: 87,
      name: "Hannah Watson",
      age: 30,
      email: "hannah.watson@example.com",
      status: "Active",
    },
    {
      id: 88,
      name: "Iris Robinson",
      age: 26,
      email: "iris.robinson@example.com",
      status: "Inactive",
    },
    {
      id: 89,
      name: "Jackie Williams",
      age: 31,
      email: "jackie.williams@example.com",
      status: "Pending",
    },
    {
      id: 90,
      name: "Kelly Lewis",
      age: 32,
      email: "kelly.lewis@example.com",
      status: "Active",
    },
    {
      id: 91,
      name: "Luke Wright",
      age: 37,
      email: "luke.wright@example.com",
      status: "Inactive",
    },
    {
      id: 92,
      name: "Mandy Scott",
      age: 28,
      email: "mandy.scott@example.com",
      status: "Pending",
    },
    {
      id: 93,
      name: "Nina Green",
      age: 30,
      email: "nina.green@example.com",
      status: "Active",
    },
    {
      id: 94,
      name: "Oscar Walker",
      age: 33,
      email: "oscar.walker@example.com",
      status: "Inactive",
    },
    {
      id: 95,
      name: "Paula Bennett",
      age: 36,
      email: "paula.bennett@example.com",
      status: "Pending",
    },
    {
      id: 96,
      name: "Quincy Hill",
      age: 40,
      email: "quincy.hill@example.com",
      status: "Active",
    },
    {
      id: 97,
      name: "Rita Walker",
      age: 34,
      email: "rita.walker@example.com",
      status: "Inactive",
    },
    {
      id: 98,
      name: "Sandra White",
      age: 29,
      email: "sandra.white@example.com",
      status: "Pending",
    },
    {
      id: 99,
      name: "Toby Adams",
      age: 37,
      email: "toby.adams@example.com",
      status: "Active",
    },
    {
      id: 100,
      name: "Ursula Reed",
      age: 28,
      email: "ursula.reed@example.com",
      status: "Inactive",
    },
    {
      id: 101,
      name: "Victor Hill",
      age: 35,
      email: "victor.hill@example.com",
      status: "Pending",
    },
  ];
  return { demoData };
}
