"""Data Transfer Object types for both ZGW APIs facing side, and our frontend."""

from ._oidc import OIDCInfo
from ._open_beheer import (
    BesluitTypeWithUUID,
    DetailResponse,
    DetailResponseWithoutVersions,
    EigenschapWithUUID,
    ExpandableZaakObjectTypeWithUUID,
    ExternalServiceError,
    FrontendFieldSet,
    FrontendFieldsets,
    InformatieObjectTypeWithUUID,
    LAXResultaat,
    OBField,
    OBFieldType,
    OBList,
    OBOption,
    OBPagedQueryParams,
    OBPagination,
    ResultaatTypeWithUUID,
    RolTypeWithUUID,
    StatusTypeWithUUID,
    VersionSummary,
    ZaakObjectTypeWithUUID,
    ZaakTypeWithUUID,
    as_ob_fieldtype,
    as_ob_option,
    make_fields_optional,
    options,
)
from ._zgw import ZGWError, ZGWResponse

__all__ = [
    "BesluitTypeWithUUID",
    "DetailResponse",
    "DetailResponseWithoutVersions",
    "EigenschapWithUUID",
    "ExpandableZaakObjectTypeWithUUID",
    "ExternalServiceError",
    "FrontendFieldSet",
    "FrontendFieldsets",
    "InformatieObjectTypeWithUUID",
    "LAXResultaat",
    "OBField",
    "OBFieldType",
    "OBList",
    "OBOption",
    "OBPagedQueryParams",
    "OBPagination",
    "OIDCInfo",
    "ResultaatTypeWithUUID",
    "RolTypeWithUUID",
    "StatusTypeWithUUID",
    "VersionSummary",
    "ZGWError",
    "ZGWResponse",
    "ZaakObjectTypeWithUUID",
    "ZaakTypeWithUUID",
    "as_ob_fieldtype",
    "as_ob_option",
    "make_fields_optional",
    "options",
]
