// TODO: INCLUDE IN BACKEND TYPES

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/procestypen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ontsluit de selectielijst procestypen.
     * @description Procestypen worden gerefereerd in zaaktypecatalogi - bij het configureren
     *     van een zaaktype wordt aangegeven welk procestype van toepassing is, zodat
     *     het archiefregime van zaken bepaald kan worden.
     *
     *     Zie https://vng.nl/files/vng/20170706-selectielijst-gemeenten-intergemeentelijke-organen-2017.pdf
     *     voor de bron van de inhoud.
     */
    get: operations["procestype_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/procestypen/{uuid}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    /**
     * Ontsluit de selectielijst procestypen.
     * @description Procestypen worden gerefereerd in zaaktypecatalogi - bij het configureren
     *     van een zaaktype wordt aangegeven welk procestype van toepassing is, zodat
     *     het archiefregime van zaken bepaald kan worden.
     *
     *     Zie https://vng.nl/files/vng/20170706-selectielijst-gemeenten-intergemeentelijke-organen-2017.pdf
     *     voor de bron van de inhoud.
     */
    get: operations["procestype_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resultaattypeomschrijvingen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Raadpleeg de generieke resultaattypeomschrijvingen.
     * @description Raadpleeg de generieke resultaattypeomschrijvingen.
     */
    get: operations["resultaattypeomschrijvinggeneriek_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resultaattypeomschrijvingen/{uuid}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unieke resource identifier (UUID4) */
        uuid: string;
      };
      cookie?: never;
    };
    /**
     * Raadpleeg de generieke resultaattypeomschrijvingen.
     * @description Raadpleeg de generieke resultaattypeomschrijvingen.
     */
    get: operations["resultaattypeomschrijvinggeneriek_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resultaten": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ontsluit de selectielijst resultaten.
     * @description Bij een procestype horen meerdere mogelijke resultaten, al dan niet
     *     generiek/specifiek. Bij het configureren van een resultaattype in het ZTC
     *     wordt aangegeven welke selectielijstklasse van toepassing is, wat een
     *     referentie is naar een item van deze resource.
     *
     *     Zie https://vng.nl/files/vng/20170706-selectielijst-gemeenten-intergemeentelijke-organen-2017.pdf
     *     voor de bron van de inhoud.
     */
    get: operations["resultaat_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resultaten/{uuid}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    /**
     * Ontsluit de selectielijst resultaten.
     * @description Bij een procestype horen meerdere mogelijke resultaten, al dan niet
     *     generiek/specifiek. Bij het configureren van een resultaattype in het ZTC
     *     wordt aangegeven welke selectielijstklasse van toepassing is, wat een
     *     referentie is naar een item van deze resource.
     *
     *     Zie https://vng.nl/files/vng/20170706-selectielijst-gemeenten-intergemeentelijke-organen-2017.pdf
     *     voor de bron van de inhoud.
     */
    get: operations["resultaat_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProcesType: {
      /**
       * Url
       * Format: uri
       * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
       */
      readonly url?: string;
      /**
       * Procestypenummer
       * @description Nummer van de selectielijstcategorie
       */
      nummer: number;
      /**
       * Jaar
       * @description Het jaartal waartoe dit ProcesType behoort
       */
      jaar: number;
      /**
       * Procestypenaam
       * @description Benaming van het procestype
       */
      naam: string;
      /**
       * Procestypeomschrijving
       * @description Omschrijving van het procestype
       */
      omschrijving: string;
      /**
       * Procestypetoelichting
       * @description Toelichting van het procestype
       */
      toelichting: string;
      /**
       * Procesobject
       * @description Object waar de uitvoering van het proces op van toepassing is en waarvan de bestaans- of geldigheidsduur eventueel van belang is bij het bepalen van de start van de bewaartermijn
       */
      procesobject: string;
    };
    Fout: {
      /**
       * Type
       * @description URI referentie naar het type fout, bedoeld voor developers
       */
      type?: string;
      /**
       * Code
       * @description Systeemcode die het type fout aangeeft
       */
      code: string;
      /**
       * Title
       * @description Generieke titel voor het type fout
       */
      title: string;
      /**
       * Status
       * @description De HTTP status code
       */
      status: number;
      /**
       * Detail
       * @description Extra informatie bij de fout, indien beschikbaar
       */
      detail: string;
      /**
       * Instance
       * @description URI met referentie naar dit specifiek voorkomen van de fout. Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
       */
      instance: string;
    };
    FieldValidationError: {
      /**
       * Name
       * @description Naam van het veld met ongeldige gegevens
       */
      name: string;
      /**
       * Code
       * @description Systeemcode die het type fout aangeeft
       */
      code: string;
      /**
       * Reason
       * @description Uitleg wat er precies fout is met de gegevens
       */
      reason: string;
    };
    ValidatieFout: {
      /**
       * Type
       * @description URI referentie naar het type fout, bedoeld voor developers
       */
      type?: string;
      /**
       * Code
       * @description Systeemcode die het type fout aangeeft
       */
      code: string;
      /**
       * Title
       * @description Generieke titel voor het type fout
       */
      title: string;
      /**
       * Status
       * @description De HTTP status code
       */
      status: number;
      /**
       * Detail
       * @description Extra informatie bij de fout, indien beschikbaar
       */
      detail: string;
      /**
       * Instance
       * @description URI met referentie naar dit specifiek voorkomen van de fout. Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
       */
      instance: string;
      invalidParams: components["schemas"]["FieldValidationError"][];
    };
    ResultaatTypeOmschrijvingGeneriek: {
      /**
       * Url
       * Format: uri
       * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
       */
      readonly url?: string;
      /**
       * Omschrijving
       * @description Algemeen gehanteerde omschrijvingen van de aard van het resultaat van zaken
       */
      omschrijving: string;
      /**
       * Definitie
       * @description Nauwkeurige beschrijving van het generieke type resultaat.
       */
      definitie: string;
      /**
       * Opmerking
       * @description Zinvolle toelichting bij de waarde van de generieke omschrijving van het resultaat.
       */
      opmerking?: string;
    };
    Resultaat: {
      /**
       * Url
       * Format: uri
       * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
       */
      readonly url?: string;
      /**
       * Proces type
       * Format: uri
       */
      readonly procesType?: string;
      /**
       * Nummer
       * @description Nummer van het resultaat. Dit wordt samengesteld met het procestype en generiek resultaat indien van toepassing.
       */
      nummer: number;
      /** Volledig nummer */
      readonly volledigNummer?: string;
      /** Generiek */
      readonly generiek?: boolean;
      /** Specifiek */
      readonly specifiek?: boolean;
      /**
       * Naam
       * @description Benaming van het procestype
       */
      naam: string;
      /**
       * Omschrijving
       * @description Omschrijving van het specifieke resultaat
       */
      omschrijving?: string;
      /**
       * Herkomst
       * @description Voorbeeld: 'Risicoanalyse', 'Systeemanalyse' of verwijzing naar Wet- en regelgeving
       */
      herkomst: string;
      /**
       * Waardering
       * @enum {string}
       */
      waardering: "blijvend_bewaren" | "vernietigen";
      /**
       * Procestermijn
       * @description Uitleg bij mogelijke waarden:
       *
       *     * `nihil` - Nihil
       *     * `bestaansduur_procesobject` - De bestaans- of geldigheidsduur van het procesobject.
       *     * `ingeschatte_bestaansduur_procesobject` - De ingeschatte maximale bestaans- of geldigheidsduur van het procesobject.
       *     * `vast_te_leggen_datum` - De tijdens het proces vast te leggen datum waarop de geldigheid van het procesobject komt te vervallen.
       *     * `samengevoegd_met_bewaartermijn` - De procestermijn is samengevoegd met de bewaartermijn.
       * @enum {string}
       */
      procestermijn?:
        | "nihil"
        | "bestaansduur_procesobject"
        | "ingeschatte_bestaansduur_procesobject"
        | "vast_te_leggen_datum"
        | "samengevoegd_met_bewaartermijn";
      /** Procestermijn weergave */
      readonly procestermijnWeergave?: string;
      /**
       * Bewaartermijn
       * Format: duration
       */
      bewaartermijn?: string | null;
      /** Toelichting */
      toelichting?: string;
      /** Algemeen bestuur en inrichting organisatie */
      algemeenBestuurEnInrichtingOrganisatie?: boolean;
      /** Bedrijfsvoering en personeel */
      bedrijfsvoeringEnPersoneel?: boolean;
      /** Publieke informatie en registratie */
      publiekeInformatieEnRegistratie?: boolean;
      /** Burgerzaken */
      burgerzaken?: boolean;
      /** Veiligheid */
      veiligheid?: boolean;
      /** Verkeer en vervoer */
      verkeerEnVervoer?: boolean;
      /** Economie */
      economie?: boolean;
      /** Onderwijs */
      onderwijs?: boolean;
      /** Sport, cultuur en recreatie */
      sportCultuurEnRecreatie?: boolean;
      /** Sociaal domein */
      sociaalDomein?: boolean;
      /** Volksgezonheid en milieu */
      volksgezonheidEnMilieu?: boolean;
      /** VHROSV */
      vhrosv?: boolean;
      /** Heffen belastingen etc. */
      heffenBelastingen?: boolean;
      /** Alle taakgebieden */
      alleTaakgebieden?: boolean;
      /**
       * Procestermijn opmerking
       * @description Voorbeeld: '25 jaar', '30 jaar, '5 of 10 jaar'
       */
      procestermijnOpmerking?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
  procestype_list: {
    parameters: {
      query?: {
        /** @description Het jaartal waartoe dit ProcesType behoort */
        jaar?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcesType"][];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ValidatieFout"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not acceptable */
      406: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Gone */
      410: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Unsupported media type */
      415: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
    };
  };
  procestype_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcesType"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not acceptable */
      406: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Gone */
      410: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Unsupported media type */
      415: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
    };
  };
  resultaattypeomschrijvinggeneriek_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResultaatTypeOmschrijvingGeneriek"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not acceptable */
      406: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Gone */
      410: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Unsupported media type */
      415: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
    };
  };
  resultaattypeomschrijvinggeneriek_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unieke resource identifier (UUID4) */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResultaatTypeOmschrijvingGeneriek"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not acceptable */
      406: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Gone */
      410: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Unsupported media type */
      415: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
    };
  };
  resultaat_list: {
    parameters: {
      query?: {
        /** @description URL naar de/het gerelateerde proces_type */
        procesType?: string;
        /** @description Een pagina binnen de gepagineerde set resultaten. */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            count: number;
            /** Format: uri */
            next?: string | null;
            /** Format: uri */
            previous?: string | null;
            results: components["schemas"]["Resultaat"][];
          };
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ValidatieFout"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not acceptable */
      406: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Gone */
      410: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Unsupported media type */
      415: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
    };
  };
  resultaat_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Resultaat"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Not acceptable */
      406: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Gone */
      410: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Unsupported media type */
      415: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
          "API-version"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Fout"];
        };
      };
    };
  };
}
