import type { Meta, StoryObj } from "@storybook/react";
import { DefaultBodyType, HttpResponse, PathParams, http } from "msw";
import {
  reactRouterParameters,
  withRouter,
} from "storybook-addon-remix-react-router";
import { API_BASE_URL } from "~/api";
import { ZaaktypeCreateLoaderData } from "~/pages";
import { routes } from "~/routes.tsx";
import { components } from "~/types";

import { ZaaktypeCreatePage as ZaaktypeCreatePageComponent } from "./";

const meta: Meta<typeof ZaaktypeCreatePageComponent> = {
  title: "Pages/ZaaktypeCreate",
  component: ZaaktypeCreatePageComponent,
  decorators: [withRouter],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const ZaaktypeCreatePage: Story = {
  parameters: {
    msw: {
      handlers: [
        http.get<
          PathParams,
          DefaultBodyType,
          components["schemas"]["ZGWResponse_Sjabloon_OptionalZaakType_"]
        >(`${API_BASE_URL}/template/zaaktype/`, () =>
          HttpResponse.json(mockedData),
        ),
      ],
    },
    reactRouter: reactRouterParameters({
      location: {
        path: `/open-zaak-catalogi-api/85028f4f-3d70-4ce9-8dbe-16a6b8613a54/zaaktypen/new`,
      },
      routing: routes[0],
    }),
  },
};

const mockedData: ZaaktypeCreateLoaderData = {
  count: 4,
  next: null,
  previous: null,
  results: [
    {
      naam: "Blanco",
      omschrijving:
        "Voor volledige vrijheid: een leeg sjabloon zonder voorgedefiniëerde structuur.",
      voorbeelden: ["van alles", "nog wat"],
      waarden: {
        url: null,
        identificatie: null,
        omschrijvingGeneriek: null,
        toelichting: null,
        servicenorm: null,
        verlengingstermijn: null,
        trefwoorden: null,
        publicatietekst: null,
        verantwoordingsrelatie: null,
        selectielijstProcestype: null,
        concept: null,
        broncatalogus: null,
        bronzaaktype: null,
        eindeGeldigheid: null,
        beginObject: null,
        eindeObject: null,
        statustypen: null,
        resultaattypen: null,
        eigenschappen: null,
        informatieobjecttypen: null,
        roltypen: null,
        deelzaaktypen: null,
        zaakobjecttypen: null,
      },
      uuid: "9b6ea0ec-735b-5cfa-ad3f-feb9ed110645",
    },
    {
      naam: "Aanvraag met besluit",
      omschrijving:
        "Voor processen waarbij een burger of bedrijf iets aanvraagt en daar een formeel besluit of volgt.",
      voorbeelden: ["parkeervergunning", "evenementenvergunning"],
      waarden: {
        omschrijving: "Aanvraag voor ...",
        vertrouwelijkheidaanduiding: "zaakvertrouwelijk",
        doel: "Besluit tot ...",
        aanleiding: "",
        indicatieInternOfExtern: "extern",
        handelingInitiator: "Aanvraag??",
        onderwerp: "",
        handelingBehandelaar: "Besluitnemen??",
        doorlooptijd: "6 weken",
        opschortingEnAanhoudingMogelijk: true,
        verlengingMogelijk: true,
        publicatieIndicatie: true,
        productenOfDiensten: [],
        referentieproces: {
          naam: "De Vries",
          link: null,
        },
        verantwoordelijke: "",
        beginGeldigheid: "",
        versiedatum: "",
        catalogus: "",
        besluittypen: [],
        gerelateerdeZaaktypen: [],
        url: null,
        identificatie: null,
        omschrijvingGeneriek: null,
        toelichting: null,
        servicenorm: null,
        verlengingstermijn: null,
        trefwoorden: null,
        publicatietekst: null,
        verantwoordingsrelatie: null,
        selectielijstProcestype: null,
        concept: null,
        broncatalogus: null,
        bronzaaktype: null,
        eindeGeldigheid: null,
        beginObject: null,
        eindeObject: null,
        statustypen: null,
        resultaattypen: null,
        eigenschappen: null,
        informatieobjecttypen: null,
        roltypen: null,
        deelzaaktypen: null,
        zaakobjecttypen: null,
      },
      uuid: "8afeaa12-5712-5484-94b4-414385ef7c25",
    },
    {
      naam: "Melding of klacht",
      omschrijving:
        "Voor processen waarbij een burger ergens melding van maakt of klacht over indient",
      voorbeelden: [
        "melding niet opgehaald vuil",
        "overlast van horeca",
        "scheuren bij bruggen",
      ],
      waarden: {
        omschrijving: "Melding van ...",
        vertrouwelijkheidaanduiding: "zaakvertrouwelijk",
        doel: "",
        aanleiding: "",
        indicatieInternOfExtern: "extern",
        handelingInitiator: "",
        onderwerp: "",
        handelingBehandelaar: "",
        doorlooptijd: "",
        opschortingEnAanhoudingMogelijk: true,
        verlengingMogelijk: true,
        publicatieIndicatie: true,
        productenOfDiensten: [],
        referentieproces: {
          naam: "Applications of process algebra",
          link: "https://cwilibrary.on.worldcat.org/oclc/24718516",
        },
        verantwoordelijke: "",
        beginGeldigheid: "",
        versiedatum: "",
        catalogus: "",
        besluittypen: [],
        gerelateerdeZaaktypen: [],
        url: null,
        identificatie: null,
        omschrijvingGeneriek: null,
        toelichting: null,
        servicenorm: null,
        verlengingstermijn: null,
        trefwoorden: null,
        publicatietekst: null,
        verantwoordingsrelatie: null,
        selectielijstProcestype: null,
        concept: null,
        broncatalogus: null,
        bronzaaktype: null,
        eindeGeldigheid: null,
        beginObject: null,
        eindeObject: null,
        statustypen: null,
        resultaattypen: null,
        eigenschappen: null,
        informatieobjecttypen: null,
        roltypen: null,
        deelzaaktypen: null,
        zaakobjecttypen: null,
      },
      uuid: "a964ba91-d8fc-5117-b542-efea32c7e54e",
    },
    {
      naam: "Interne procedure",
      omschrijving:
        "Voor Interne gemeentelijke of organisatorische werkstromen.",
      voorbeelden: [
        "inkoopaanvraag",
        "medewerker onboarding",
        "contractverlenging",
      ],
      waarden: {
        omschrijving: "",
        vertrouwelijkheidaanduiding: "zaakvertrouwelijk",
        doel: "",
        aanleiding: "",
        indicatieInternOfExtern: "intern",
        handelingInitiator: "",
        onderwerp: "",
        handelingBehandelaar: "",
        doorlooptijd: "",
        opschortingEnAanhoudingMogelijk: false,
        verlengingMogelijk: false,
        publicatieIndicatie: true,
        productenOfDiensten: [],
        referentieproces: {
          naam: "PCDA",
          link: "https://www.gemmaonline.nl/wiki/Procesarchitectuur_Besturing_en_procesverbetering#De_PDCA-cyclus",
        },
        verantwoordelijke: "",
        beginGeldigheid: "",
        versiedatum: "",
        catalogus: "",
        besluittypen: [],
        gerelateerdeZaaktypen: [],
        url: null,
        identificatie: null,
        omschrijvingGeneriek: null,
        toelichting: null,
        servicenorm: null,
        verlengingstermijn: null,
        trefwoorden: null,
        publicatietekst: null,
        verantwoordingsrelatie: null,
        selectielijstProcestype: null,
        concept: null,
        broncatalogus: null,
        bronzaaktype: null,
        eindeGeldigheid: null,
        beginObject: null,
        eindeObject: null,
        statustypen: null,
        resultaattypen: null,
        eigenschappen: null,
        informatieobjecttypen: null,
        roltypen: null,
        deelzaaktypen: null,
        zaakobjecttypen: null,
      },
      uuid: "fd71db9a-9b39-58f8-8fb6-3a5720fda4cd",
    },
  ],
};
