# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------
import os
import sys
import django
import pathlib

root_folder = pathlib.Path(__file__).parent.parent
src_folder = (root_folder / pathlib.Path("backend") / pathlib.Path("src") )

sys.path.insert(0, str(src_folder))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "openbeheer.conf.ci")
django.setup()

import openbeheer  # noqa isort:skip

# -- Project information -----------------------------------------------------

project = "openbeheer"
copyright = "Maykin B.V. 2025"
author = openbeheer.__author__

# The full version, including alpha/beta/rc tags
release = openbeheer.__version__


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # "sphinx.ext.todo",
    # "sphinx_tabs.tabs",
    # "recommonmark",
    # "sphinx_markdown_tables",
    "sphinx.ext.autodoc",
    "django_setup_configuration.documentation.setup_config_example",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

source_suffix = [".rst", ".md"]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_logo = "logo.png"
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "theme_overrides.css",  # override wide tables with word wrap
]

todo_include_todos = True

linkcheck_ignore = [
    r"https?://.*\.example.com*",
    r"http://localhost:\d+/",
    r"https://.*sentry.*",
    "https://www.npmjs.com/"
]
