#
# DISCLAIMER: THIS IS FOR DEVELOPMENT PURPOSES ONLY AND NOT SUITABLE FOR PRODUCTION.
#
# You can use this docker-compose to spin up a local stack for demo/try-out
# purposes, or to get some insight in the various components involved (e.g. to build
# your Helm charts from). Note that various environment variables are UNSAFE and merely
# specified so that you can get up and running with the least amount of friction.
services:
  keycloak.local:
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:26.3.2
    ports:
      - "28080:8080"
    restart: unless-stopped
    volumes:
      - ./fixtures:/opt/keycloak/data/import
    networks:
      - keycloak-dev

networks:
  keycloak-dev:
    name: keycloak-dev