name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
    paths:
      - "**.py"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "**.in"
  pull_request:
    paths:
      - "**.py"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "**.in"
  workflow_dispatch:

jobs:
  migrations:
    name: Check for model changes not present in migrations
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgis/postgis:14-3.4
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up backend environment
        uses: maykinmedia/setup-django-backend@v1.3
        with:
          apt-packages: "gettext postgresql-client"
          python-version: "3.12"
          setup-node: "no"
          working-directory: backend
      - name: Run makemigrations to check for missing migrations
        working-directory: backend
        run: |
          src/manage.py makemigrations \
            --check \
            --dry-run
        env:
          DJANGO_SETTINGS_MODULE: "openbeheer.conf.ci"
          DEBUG: "true"
          SECRET_KEY: dummy
          DB_USER: postgres
          DB_NAME: postgres
          DB_PASSWORD: ""

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Linting
        run: ruff check
      - name: Check formatting
        run: ruff format --check
